/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterIcons {
  MyFlutterIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData sort_name_up = IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_name_down = IconData(0xf15e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alt_up = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alt_down = IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_number_up = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_number_down = IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
